apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/krishnasai111/Jenkins-Zero-To-Hero/blob/main/java-maven-sonar-argocd-helm-k8s'
    targetRevision: HEAD
    path: 'spring-boot-app-manifestss'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: '35.170.243.139:6443'  # Replace with your EC2 IP
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
