apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/krishnasai111/Jenkins-Zero-To-Hero'
    targetRevision: HEAD
    path: 'spring-boot-app-manifestss'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: '44.204.41.35:6443'  # Replace with your EC2 IP
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
