# Image configuration
image:
  repository: 440588537421.dkr.ecr.us-east-1.amazonaws.com/cicd
  tag: 67

# Environment variables
env:
  profile: "prod"

# Service configuration
service:
  type: LoadBalancer
  port: 80

